import { useState, useMemo, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ArrowLeft, Download, User, Check } from 'lucide-react';
import { useRubricStore } from '@/hooks/useRubricStore';
import { StatusBadge } from '@/components/StatusBadge';
import { cn } from '@/lib/utils';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function GradingView() {
  const { rubricId } = useParams();
  const navigate = useNavigate();
  const { getRubricById } = useRubricStore();
  
  const rubric = getRubricById(rubricId || '');
  
  const [studentName, setStudentName] = useState('');
  const [selections, setSelections] = useState<{ [rowId: string]: string }>({});

  const handleCellClick = useCallback((rowId: string, columnId: string) => {
    setSelections((prev) => ({
      ...prev,
      [rowId]: prev[rowId] === columnId ? '' : columnId,
    }));
  }, []);

  const { totalScore, rowScores } = useMemo(() => {
    if (!rubric) return { totalScore: 0, rowScores: {} };
    
    const rowScores: { [rowId: string]: number } = {};
    let total = 0;
    
    rubric.rows.forEach((row) => {
      const selectedColumnId = selections[row.id];
      if (selectedColumnId) {
        const column = rubric.columns.find((c) => c.id === selectedColumnId);
        if (column) {
          rowScores[row.id] = column.points;
          total += column.points;
        }
      } else {
        rowScores[row.id] = 0;
      }
    });
    
    return { totalScore: total, rowScores };
  }, [rubric, selections]);

  const currentStatus = useMemo(() => {
    if (!rubric) return null;
    
    for (const threshold of rubric.thresholds) {
      if (totalScore >= threshold.min && totalScore <= threshold.max) {
        return threshold;
      }
    }
    return rubric.thresholds[0] || null;
  }, [rubric, totalScore]);

  const getCriteriaValue = (rowId: string, columnId: string) => {
    return rubric?.criteria.find((c) => c.rowId === rowId && c.columnId === columnId)?.description || '';
  };

  const exportToPDF = () => {
    if (!rubric) return;

    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(13, 148, 136); // Primary teal color
    doc.text(rubric.name, 14, 20);
    
    // Student info
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Student: ${studentName || 'Not specified'}`, 14, 32);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 40);
    
    // Score and Status
    doc.setFontSize(14);
    doc.text(`Total Score: ${totalScore} / ${rubric.totalPossiblePoints} points`, 14, 52);
    doc.text(`Status: ${currentStatus?.label || 'N/A'}`, 14, 60);
    
    // Rubric table
    const tableData = rubric.rows.map((row) => {
      const selectedColumnId = selections[row.id];
      const selectedColumn = rubric.columns.find((c) => c.id === selectedColumnId);
      const criteria = selectedColumnId ? getCriteriaValue(row.id, selectedColumnId) : '-';
      
      return [
        row.name,
        selectedColumn?.name || '-',
        criteria,
        `${rowScores[row.id] || 0} pts`,
      ];
    });

    autoTable(doc, {
      startY: 70,
      head: [['Learning Goal', 'Level', 'Criteria', 'Points']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [13, 148, 136],
        textColor: 255,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 30 },
        2: { cellWidth: 80 },
        3: { cellWidth: 25 },
      },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Generated by Rubric Grader - Page ${i} of ${pageCount}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    doc.save(`${rubric.name}_${studentName || 'rubric'}.pdf`);
  };

  if (!rubric) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Card className="max-w-md">
          <CardContent className="pt-6 text-center">
            <p className="text-muted-foreground mb-4">Rubric not found</p>
            <Button onClick={() => navigate('/')}>Go Back</Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const allRowsSelected = rubric.rows.every((row) => selections[row.id]);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Button variant="ghost" onClick={() => navigate('/')} className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
            <h1 className="text-lg font-semibold truncate max-w-[200px] md:max-w-none">
              {rubric.name}
            </h1>
            <Button onClick={exportToPDF} className="gap-2" disabled={!allRowsSelected}>
              <Download className="h-4 w-4" />
              <span className="hidden sm:inline">Export PDF</span>
            </Button>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-6">
        <div className="grid gap-6 lg:grid-cols-4">
          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-4">
            <Card className="shadow-soft">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <User className="h-4 w-4" />
                  Student Info
                </CardTitle>
              </CardHeader>
              <CardContent>
                <Label htmlFor="student-name" className="sr-only">Student Name</Label>
                <Input
                  id="student-name"
                  placeholder="Enter student name..."
                  value={studentName}
                  onChange={(e) => setStudentName(e.target.value)}
                />
              </CardContent>
            </Card>

            <Card className="shadow-soft">
              <CardHeader className="pb-3">
                <CardTitle className="text-base">Score</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="text-center">
                  <p className="text-4xl font-bold text-primary">{totalScore}</p>
                  <p className="text-sm text-muted-foreground">
                    of {rubric.totalPossiblePoints} points
                  </p>
                </div>
                <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
                  <div
                    className={cn(
                      "h-full rounded-full transition-all duration-500",
                      currentStatus?.status === 'expert' && "bg-status-expert",
                      currentStatus?.status === 'mastered' && "bg-status-mastered",
                      currentStatus?.status === 'development' && "bg-status-development"
                    )}
                    style={{
                      width: `${rubric.totalPossiblePoints > 0 
                        ? (totalScore / rubric.totalPossiblePoints) * 100 
                        : 0}%`,
                    }}
                  />
                </div>
                {currentStatus && (
                  <div className="flex justify-center">
                    <StatusBadge status={currentStatus.status} size="lg" />
                  </div>
                )}
              </CardContent>
            </Card>

            <Card className="shadow-soft">
              <CardHeader className="pb-3">
                <CardTitle className="text-base">Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground text-center">
                  {Object.keys(selections).filter((k) => selections[k]).length} of {rubric.rows.length} goals graded
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Main Grid */}
          <div className="lg:col-span-3">
            <Card className="shadow-soft">
              <CardContent className="p-0">
                <ScrollArea className="w-full">
                  <div className="min-w-max p-4">
                    <table className="w-full border-collapse">
                      <thead>
                        <tr>
                          <th className="sticky left-0 z-10 bg-grid-header p-4 text-left font-semibold border-b min-w-[180px]">
                            Learning Goal
                          </th>
                          {rubric.columns.map((col) => (
                            <th
                              key={col.id}
                              className="bg-grid-header p-4 text-center font-semibold border-b min-w-[150px]"
                            >
                              {col.name}
                              <span className="block text-xs font-normal text-muted-foreground">
                                {col.points} pts
                              </span>
                            </th>
                          ))}
                          <th className="bg-grid-header p-4 text-center font-semibold border-b min-w-[80px]">
                            Score
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {rubric.rows.map((row) => (
                          <tr key={row.id} className="group">
                            <td className="sticky left-0 z-10 bg-card p-4 font-medium border-b group-hover:bg-muted/50 transition-colors">
                              {row.name}
                            </td>
                            {rubric.columns.map((col) => {
                              const isSelected = selections[row.id] === col.id;
                              const criteria = getCriteriaValue(row.id, col.id);
                              
                              return (
                                <td key={col.id} className="border-b p-2">
                                  <button
                                    onClick={() => handleCellClick(row.id, col.id)}
                                    className={cn(
                                      "w-full min-h-[80px] rounded-lg border-2 p-3 text-sm transition-all duration-200",
                                      "hover:border-primary/50 hover:bg-primary/5",
                                      isSelected
                                        ? "border-primary bg-primary/10 ring-2 ring-primary/20"
                                        : "border-transparent bg-muted/30"
                                    )}
                                  >
                                    {isSelected && (
                                      <div className="flex items-center justify-center mb-2">
                                        <div className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-primary-foreground">
                                          <Check className="h-4 w-4" />
                                        </div>
                                      </div>
                                    )}
                                    <p className={cn(
                                      "text-xs leading-relaxed",
                                      isSelected ? "text-foreground" : "text-muted-foreground"
                                    )}>
                                      {criteria || <em className="opacity-50">No criteria</em>}
                                    </p>
                                  </button>
                                </td>
                              );
                            })}
                            <td className="border-b p-4 text-center">
                              <span className={cn(
                                "inline-flex h-10 w-16 items-center justify-center rounded-lg font-bold transition-all",
                                rowScores[row.id] > 0 
                                  ? "bg-primary/10 text-primary" 
                                  : "bg-muted text-muted-foreground"
                              )}>
                                {rowScores[row.id] || 0}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot>
                        <tr>
                          <td
                            colSpan={rubric.columns.length + 1}
                            className="sticky left-0 bg-card p-4 text-right font-semibold"
                          >
                            Total Score:
                          </td>
                          <td className="p-4 text-center">
                            <span className="inline-flex h-12 w-20 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground">
                              {totalScore}
                            </span>
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </ScrollArea>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
